---
provisioner:
  name: ansible_playbook
  hosts: all
  require_chef_for_busser: false
  require_ruby_for_busser: false
  require_pip3: true
  ansible_binary_path: /usr/local/bin
  ansible_verbose: true
  roles_path: spec/ansible/roles/
  galaxy_ignore_certs: true
  env_vars:
    - ANSIBLE_LOCAL_TEMP=$HOME/.ansible/tmp
    - ANSIBLE_REMOTE_TEMP=$HOME/.ansible/tmp

transport:
  name: ssh
  max_ssh_sessions: 2

lifecycle:
  pre_converge:
    - remote: |
        echo "NOTICE - Updating the vagrant user to keep sudo working"
        sudo chage -d $(( $( date +%s ) / 86400 )) vagrant
        echo "NOTICE - Updating root passwd"
        echo 'password' | sudo passwd --stdin root
        echo "NOTICE - updating vagrant sudo config"
        sudo chmod 600 /etc/sudoers && sudo sed -i'' "/vagrant/d" /etc/sudoers && sudo chmod 400 /etc/sudoers

verifier:
  name: inspec
  sudo: true
  reporter:
    - cli
    - json:spec/results/%{platform}_%{suite}.json
  inspec_tests:
    - name: Ubuntu 20.04 LTS STIG V1R5
      path: .
  load_plugins: true

platforms:
  - name: ubuntu-20.04

suites:
  - name: hardened
    provisioner:
      playbook: spec/ansible/roles/hardening.yml
