---
provisioner:
  name: ansible_playbook
  hosts: all
  require_chef_for_busser: false
  require_ruby_for_busser: false
  require_ansible_repo: true
  ansible_verbose: true
  ansible_verbosity: 3
  ansible_version: latest
  galaxy_ignore_certs: true
  roles_path: spec/ansible/roles/
  env_vars:
    - ANSIBLE_LOCAL_TEMP=$HOME/.ansible/tmp
    - ANSIBLE_REMOTE_TEMP=$HOME/.ansible/tmp

transport:
  name: ssh
  max_ssh_sessions: 2

verifier:
  name: inspec
  sudo: true
  reporter:
    - cli
    - json:spec/results/ubuntu-2004_%{suite}.json
  inspec_tests:
    - name: Ubuntu 20.04 LTS STIG V1R5
      path: .
  load_plugins: true

platforms:
  - name: ubuntu-20.04

suites:
  - name: hardened
    provisioner:
      playbook: spec/ansible/roles/hardening.yml
  # - name: vanilla
  #   provisioner:
  #     playbook: spec/ansible/roles/vanilla.yml
