roles:
  - name: ubuntu20STIG
    src: https://github.com/ansible-lockdown/UBUNTU20-STIG
    version: 1.1.2

collections:
  - name: community.general
    source: https://galaxy.ansible.com
  - name: community.crypto
    source: https://galaxy.ansible.com
  - name: ansible.posix
    source: https://galaxy.ansible.com
