name: Build Profile Archive

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build Profile Archive
    uses: mitre/inspec-profile-workflows/.github/workflows/build.yml@4cf2d1cfd4aca2072eb9bf849a363b76792c0693
