name: Request Profile Release

on:
  workflow_dispatch:
    inputs:
      build-run-id:
        description: Optional build run ID. Leave blank for the latest successful main push build.
        required: false
        type: string

permissions:
  contents: read

jobs:
  release:
    name: Request Profile Release
    permissions:
      contents: write
      actions: read
    uses: mitre/inspec-profile-workflows/.github/workflows/release.yml@64511f94449af6803dba42c091f1da7340b83a5a
    with:
      build-run-id: ${{ inputs.build-run-id }}
      build-workflow: build.yml
