name: Container Testing Matrix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate my profile
    runs-on: ubuntu-latest
    env:
      CHEF_LICENSE: accept-silent
      KITCHEN_LOCAL_YAML: kitchen.container.yml
      LC_ALL: "en_US.UTF-8"
      VANILLA_IMAGE: "public.ecr.aws/lts/ubuntu:focal"
      HARDENED_IMAGE: "canonical/ubuntu-pro-stig-20.04:latest"
    strategy:
      fail-fast: false
    steps:
      - name: add needed packages
        run: sudo apt-get install -y jq
      - name: Checkout InSpec profile repository
        uses: actions/checkout@v2
      - name: Clone full repository so we can push
        run: git fetch --prune --unshallow
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Disable ri and rdoc
        run: 'echo "gem: --no-ri --no-rdoc" >> ~/.gemrc'
      - run: bundle install
      # - name: Regenerate current `profile.json`
      #   run: |
      #     bundle exec inspec json . | jq . > profile.json
      - name: Lint the Inspec profile
        run: bundle exec inspec check .
      -name: Build the Hardened Container
        run: docker build https://repo1.dso.mil/dsop/canonical/ubuntu/ubuntu-pro-cis-stig-20.04.git\#development --tag $HARDENED_IMAGE
      - name: Start the Vanilla Container
        run: docker run -itd --rm --name vanilla-ubuntu $VANILLA_IMAGE
      - name: Start the Hardened Container
        run: docker run -itd --rm --name hardened-ubuntu $HARDENED_IMAGE
      - name: Verify both our containers are running
        run: docker ps -f name=-ubuntu
      - name: Test $VANILLA_IMAGE
        run: inspec exec . --input-file=container.inputs.yml -t docker://vanilla-ubuntu --reporter json:vanilla.json progress-bar
      # # - name: Run kitchen test
      # #   run: bundle exec kitchen test --destroy=always ${{ matrix.suite }}-ubuntu-2004 || true
      # - name: Display our ${{ matrix.suite }} results summary
      #   uses: mitre/saf_action@v1
      #   with:
      #     command_string: 'view summary -i spec/results/container_ubuntu-2004_${{ matrix.suite }}.json'
      # - name: Ensure the scan meets our ${{ matrix.suite }} results threshold
      #   uses: mitre/saf_action@v1
      #   with:
      #     command_string: 'validate threshold -i spec/results/container_ubuntu-2004_${{ matrix.suite }}.json -F ${{ matrix.suite }}.threshold.yml'
      # - name: Save Test Result JSONs
      #   if: ${{ always() }}
      #   uses: actions/upload-artifact@v2
      #   with:
      #     path: spec/results/
